services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
      
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
      
  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile
      
  catalog.db:
      image: mongo

  basket.db:
      image: redis:alpine
      
  discount.db:
      image: postgres
      
  postgres-monitor:
    image: dpage/pgadmin4
  
  mongo-monitor:
    image: mongo-express
        
volumes:
  mongo_data:
    driver: local
      
  redis_data:
    driver: local
      
  postgres_monitor_session:
    driver: local
      
  postgres_data:
    driver: local
