version: '3.4' 

services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  catalog.db:
      image: mongo
        
volumes:
    mongo_data:
        driver: local
