version: '3.4'

services:
  catalog.db:  
    container_name: catalogDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
  catalog.api:
    container_name: catalog.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:80
        - DatabaseSettings_ConnectionString=mongodb://catalogDb:27017
    depends_on: 
        - catalog.db
    ports:
      - "80:80"
        

